
const Discord = require('discord.js');
const MrFOG1 = new Discord.Client();
const MrFOG2 = new Discord.Client();
const MrFOG3 = new Discord.Client();
const MrFOG4 = new Discord.Client();
const MrFOG5 = new Discord.Client();
const MrFOG6 = new Discord.Client();
const MrFOG7 = new Discord.Client();
const MrFOG8 = new Discord.Client();
const MrFOG9 = new Discord.Client();
const MrFOG10 = new Discord.Client();
const MrFOG11 = new Discord.Client();
const MrFOG12 = new Discord.Client();
const MrFOG13 = new Discord.Client();
const MrFOG14 = new Discord.Client();
const MrFOG15 = new Discord.Client();
const MrFOG16 = new Discord.Client();
const MrFOG17 = new Discord.Client();
const MrFOG18 = new Discord.Client();
const MrFOG19 = new Discord.Client();
const MrFOG20 = new Discord.Client();
const MrFOG21 = new Discord.Client();
const MrFOG22 = new Discord.Client();
const MrFOG23 = new Discord.Client();
const MrFOG24 = new Discord.Client();
const MrFOG25 = new Discord.Client();
const MrFOG26 = new Discord.Client();
const MrFOG27 = new Discord.Client();
const MrFOG28 = new Discord.Client();
const MrFOG29 = new Discord.Client();
const MrFOG30 = new Discord.Client();
const MrFOG31 = new Discord.Client();
const MrFOG32 = new Discord.Client();
const MrFOG33 = new Discord.Client();
const MrFOG34 = new Discord.Client();
const MrFOG35 = new Discord.Client();
const MrFOG36 = new Discord.Client();
const MrFOG37 = new Discord.Client();
const MrFOG38 = new Discord.Client();
const MrFOG39 = new Discord.Client();
const MrFOG40 = new Discord.Client();
const MrFOG41 = new Discord.Client();
const MrFOG42 = new Discord.Client();
const MrFOG43 = new Discord.Client();
const MrFOG44 = new Discord.Client();
const MrFOG45 = new Discord.Client();
const MrFOG46 = new Discord.Client();
const MrFOG47 = new Discord.Client();
const MrFOG48 = new Discord.Client();
const MrFOG49 = new Discord.Client();
const MrFOG50 = new Discord.Client();
const MrFOG51 = new Discord.Client();
const MrFOG52 = new Discord.Client();
const MrFOG53 = new Discord.Client();
const MrFOG54 = new Discord.Client();
const MrFOG55 = new Discord.Client();
const MrFOG56 = new Discord.Client();
const MrFOG57 = new Discord.Client();
const MrFOG58 = new Discord.Client();
const MrFOG59 = new Discord.Client();
const MrFOG60 = new Discord.Client();
const MrFOG61 = new Discord.Client();
const MrFOG62 = new Discord.Client();
const MrFOG63 = new Discord.Client();
const MrFOG64 = new Discord.Client();
const MrFOG65 = new Discord.Client();
const MrFOG66 = new Discord.Client();
const MrFOG67 = new Discord.Client();
const MrFOG68 = new Discord.Client();
const MrFOG69 = new Discord.Client();
const MrFOG70 = new Discord.Client();
const MrFOG71 = new Discord.Client();
const MrFOG72 = new Discord.Client();
const MrFOG73 = new Discord.Client();
const MrFOG74 = new Discord.Client();
const MrFOG75 = new Discord.Client();
const MrFOG76 = new Discord.Client();
const MrFOG77 = new Discord.Client();
const MrFOG78 = new Discord.Client();
const MrFOG79 = new Discord.Client();
const MrFOG80 = new Discord.Client();
const MrFOG81 = new Discord.Client();
const MrFOG82 = new Discord.Client();
const MrFOG83 = new Discord.Client();
const MrFOG84 = new Discord.Client();
const MrFOG85 = new Discord.Client();
const MrFOG86 = new Discord.Client();
const MrFOG87 = new Discord.Client();
const MrFOG88 = new Discord.Client();
const MrFOG89 = new Discord.Client();
const MrFOG90 = new Discord.Client();
const MrFOG91 = new Discord.Client();
const MrFOG92 = new Discord.Client();
const MrFOG93 = new Discord.Client();
const MrFOG94 = new Discord.Client();
const MrFOG95 = new Discord.Client();
const MrFOG96 = new Discord.Client();
const MrFOG97 = new Discord.Client();
const MrFOG98 = new Discord.Client();
const MrFOG99 = new Discord.Client();
const MrFOG100= new Discord.Client();
const MrFOG101= new Discord.Client();
const MrFOG102= new Discord.Client();
const MrFOG103= new Discord.Client();
const MrFOG104= new Discord.Client();
const MrFOG105= new Discord.Client();
const MrFOG106= new Discord.Client();
const MrFOG107= new Discord.Client();
const MrFOG108= new Discord.Client();
const MrFOG109= new Discord.Client();
const MrFOG110= new Discord.Client();
const MrFOG111= new Discord.Client();
const MrFOG112= new Discord.Client();
const MrFOG113= new Discord.Client();
const MrFOG114= new Discord.Client();
const MrFOG115= new Discord.Client();
const MrFOG116= new Discord.Client();
const MrFOG117= new Discord.Client();
const MrFOG118= new Discord.Client();
const MrFOG119= new Discord.Client();
const MrFOG120= new Discord.Client();
const MrFOG121= new Discord.Client();
const MrFOG122= new Discord.Client();
const MrFOG123= new Discord.Client();
const MrFOG124= new Discord.Client();
const MrFOG125= new Discord.Client();
const MrFOG126= new Discord.Client();
const MrFOG127= new Discord.Client();
const MrFOG128= new Discord.Client();
const MrFOG129= new Discord.Client();
const MrFOG130= new Discord.Client();
const MrFOG131= new Discord.Client();
const MrFOG132= new Discord.Client();
const MrFOG133= new Discord.Client();
const MrFOG134= new Discord.Client();
const MrFOG135= new Discord.Client();
const MrFOG136= new Discord.Client();
const MrFOG137= new Discord.Client();
const MrFOG138= new Discord.Client();
const MrFOG139= new Discord.Client();
const MrFOG140= new Discord.Client();
const MrFOG141= new Discord.Client();
const MrFOG142= new Discord.Client();
const MrFOG143= new Discord.Client();
const MrFOG144= new Discord.Client();
const MrFOG145= new Discord.Client();
const MrFOG146= new Discord.Client();
const MrFOG147= new Discord.Client();
const MrFOG148= new Discord.Client();
const MrFOG149= new Discord.Client();
const MrFOG150= new Discord.Client();
const MrFOG151= new Discord.Client();
const MrFOG152= new Discord.Client();
const MrFOG153= new Discord.Client();
const MrFOG154= new Discord.Client();
const MrFOG155= new Discord.Client();
const MrFOG156= new Discord.Client();
const MrFOG157= new Discord.Client();
const MrFOG158= new Discord.Client();
const MrFOG159= new Discord.Client();
const MrFOG160= new Discord.Client();
const MrFOG161= new Discord.Client();
const MrFOG162= new Discord.Client();
const MrFOG163= new Discord.Client();
const MrFOG164= new Discord.Client();
const MrFOG165= new Discord.Client();
const MrFOG166= new Discord.Client();
const MrFOG167= new Discord.Client();
const MrFOG168= new Discord.Client();
const MrFOG169= new Discord.Client();
const MrFOG170= new Discord.Client();
const MrFOG171= new Discord.Client();
const MrFOG172= new Discord.Client();
const MrFOG173= new Discord.Client();
const MrFOG174= new Discord.Client();
const MrFOG175= new Discord.Client();
const MrFOG176= new Discord.Client();
const MrFOG177= new Discord.Client();
const MrFOG178= new Discord.Client();
const MrFOG179= new Discord.Client();
const MrFOG180= new Discord.Client();
const MrFOG181= new Discord.Client();
const MrFOG182= new Discord.Client();
const MrFOG183= new Discord.Client();
const MrFOG184= new Discord.Client();
const MrFOG185= new Discord.Client();
const MrFOG186= new Discord.Client();
const MrFOG187= new Discord.Client();
const MrFOG188= new Discord.Client();
const MrFOG189= new Discord.Client();
const MrFOG190= new Discord.Client();
const MrFOG191= new Discord.Client();
const MrFOG192= new Discord.Client();
const MrFOG193= new Discord.Client();
const MrFOG194= new Discord.Client();
const MrFOG195= new Discord.Client();
const MrFOG196= new Discord.Client();
const MrFOG197= new Discord.Client();
const MrFOG198= new Discord.Client();
const MrFOG199= new Discord.Client();
const MrFOG200= new Discord.Client();
const MrFOG201= new Discord.Client();
const MrFOG202= new Discord.Client();
const MrFOG203= new Discord.Client();
const MrFOG204= new Discord.Client();
const MrFOG205= new Discord.Client();
const MrFOG206= new Discord.Client();
const MrFOG207= new Discord.Client();
const MrFOG208= new Discord.Client();
const MrFOG209= new Discord.Client();
const MrFOG210= new Discord.Client();
const MrFOG211= new Discord.Client();
const MrFOG212= new Discord.Client();
const MrFOG213= new Discord.Client();
const MrFOG214= new Discord.Client();
const MrFOG215= new Discord.Client();
const MrFOG216= new Discord.Client();
const MrFOG217= new Discord.Client();
const MrFOG218= new Discord.Client();
const MrFOG219= new Discord.Client();
const MrFOG220= new Discord.Client();
const MrFOG221= new Discord.Client();
const MrFOG222= new Discord.Client();
const MrFOG223= new Discord.Client();
const MrFOG224= new Discord.Client();
const MrFOG225= new Discord.Client();
const MrFOG226= new Discord.Client();
const MrFOG227= new Discord.Client();
const MrFOG228= new Discord.Client();
const MrFOG229= new Discord.Client();
const MrFOG230= new Discord.Client();
const MrFOG231= new Discord.Client();
const MrFOG232= new Discord.Client();
const MrFOG233= new Discord.Client();
const MrFOG234= new Discord.Client();
const MrFOG235= new Discord.Client();
const MrFOG236= new Discord.Client();
const MrFOG237= new Discord.Client();
const MrFOG238= new Discord.Client();
const MrFOG239= new Discord.Client();
const MrFOG240= new Discord.Client();
const MrFOG241= new Discord.Client();
const MrFOG242= new Discord.Client();
const MrFOG243= new Discord.Client();
const MrFOG244= new Discord.Client();
const MrFOG245= new Discord.Client();
const MrFOG246= new Discord.Client();
const MrFOG247= new Discord.Client();
const MrFOG248= new Discord.Client();
const MrFOG249= new Discord.Client();
const MrFOG250= new Discord.Client();
const MrFOG251= new Discord.Client();
const MrFOG252= new Discord.Client();
const MrFOG253= new Discord.Client();
const MrFOG254= new Discord.Client();
const MrFOG255= new Discord.Client();
const MrFOG256= new Discord.Client();
const MrFOG257= new Discord.Client();
const MrFOG258= new Discord.Client();
const MrFOG259= new Discord.Client();
const MrFOG260= new Discord.Client();
const MrFOG261= new Discord.Client();
const MrFOG262= new Discord.Client();
const MrFOG263= new Discord.Client();
const MrFOG264= new Discord.Client();
const MrFOG265= new Discord.Client();
const MrFOG266= new Discord.Client();
const MrFOG267= new Discord.Client();
const MrFOG268= new Discord.Client();
const MrFOG269= new Discord.Client();
const MrFOG270= new Discord.Client();
const MrFOG271= new Discord.Client();
const MrFOG272= new Discord.Client();
const MrFOG273= new Discord.Client();
const MrFOG274= new Discord.Client();
const MrFOG275= new Discord.Client();
const MrFOG276= new Discord.Client();
const MrFOG277= new Discord.Client();
const MrFOG278= new Discord.Client();
const MrFOG279= new Discord.Client();
const MrFOG280= new Discord.Client();
const MrFOG282= new Discord.Client();
const MrFOG283= new Discord.Client();
const MrFOG284= new Discord.Client();
const MrFOG285= new Discord.Client();
const MrFOG286= new Discord.Client();
const MrFOG287= new Discord.Client();
const MrFOG288= new Discord.Client();
const MrFOG289= new Discord.Client();
const MrFOG290= new Discord.Client();
const MrFOG291= new Discord.Client();
const MrFOG292= new Discord.Client();
const MrFOG293= new Discord.Client();
const MrFOG294= new Discord.Client();
const MrFOG295= new Discord.Client();
const MrFOG296= new Discord.Client();
const MrFOG297= new Discord.Client();
const MrFOG298= new Discord.Client();
const MrFOG299= new Discord.Client();
const MrFOG300= new Discord.Client();
const MrFOG301= new Discord.Client();
const MrFOG302= new Discord.Client();
const MrFOG303= new Discord.Client();
const MrFOG304= new Discord.Client();
const MrFOG305= new Discord.Client();
const MrFOG306= new Discord.Client();
const MrFOG307= new Discord.Client();
const MrFOG308= new Discord.Client();
const MrFOG309= new Discord.Client();
const MrFOG310= new Discord.Client();
const MrFOG311= new Discord.Client();
const MrFOG312= new Discord.Client();
const MrFOG313= new Discord.Client();
const MrFOG314= new Discord.Client();
const MrFOG315= new Discord.Client();
const MrFOG316= new Discord.Client();
const MrFOG317= new Discord.Client();
const MrFOG318= new Discord.Client();
const MrFOG319= new Discord.Client();
const MrFOG320= new Discord.Client();
const MrFOG321= new Discord.Client();
const MrFOG322= new Discord.Client();
const MrFOG323= new Discord.Client();
const MrFOG324= new Discord.Client();
const MrFOG325= new Discord.Client();
const MrFOG326= new Discord.Client();
const MrFOG327= new Discord.Client();
const MrFOG328= new Discord.Client();
const MrFOG329= new Discord.Client();
const MrFOG330= new Discord.Client();
const MrFOG331= new Discord.Client();
const MrFOG332= new Discord.Client();
const MrFOG333= new Discord.Client();
const MrFOG334= new Discord.Client();
const MrFOG335= new Discord.Client();
const MrFOG336= new Discord.Client();
const MrFOG337= new Discord.Client();
const MrFOG338= new Discord.Client();
const MrFOG339= new Discord.Client();
const MrFOG340= new Discord.Client();
const MrFOG341= new Discord.Client();
const MrFOG342= new Discord.Client();
const MrFOG343= new Discord.Client();
const MrFOG344= new Discord.Client();
const MrFOG345= new Discord.Client();
const MrFOG346= new Discord.Client();
const MrFOG347= new Discord.Client();
const MrFOG348= new Discord.Client();
const MrFOG349= new Discord.Client();
const MrFOG350= new Discord.Client();
const MrFOG351= new Discord.Client();
const MrFOG352= new Discord.Client();
const MrFOG353= new Discord.Client();
const MrFOG354= new Discord.Client();
const MrFOG355= new Discord.Client();
const MrFOG356= new Discord.Client();
const MrFOG357= new Discord.Client();
const MrFOG358= new Discord.Client();
const MrFOG359= new Discord.Client();
const MrFOG360= new Discord.Client();
const MrFOG361= new Discord.Client();
const MrFOG362= new Discord.Client();
const MrFOG363= new Discord.Client();
const MrFOG364= new Discord.Client();
const MrFOG365= new Discord.Client();
const MrFOG366= new Discord.Client();
const MrFOG367= new Discord.Client();
const MrFOG368= new Discord.Client();
const MrFOG369= new Discord.Client();
const MrFOG370= new Discord.Client();
const MrFOG371= new Discord.Client();
const MrFOG372= new Discord.Client();
const MrFOG373= new Discord.Client();
const MrFOG374= new Discord.Client();
const MrFOG375= new Discord.Client();
const MrFOG376= new Discord.Client();
const MrFOG377= new Discord.Client();
const MrFOG378= new Discord.Client();
const MrFOG379= new Discord.Client();
const MrFOG380= new Discord.Client();
const MrFOG381= new Discord.Client();
const MrFOG382= new Discord.Client();
const MrFOG383= new Discord.Client();
const MrFOG384= new Discord.Client();
const MrFOG385= new Discord.Client();
const MrFOG386= new Discord.Client();
const MrFOG387= new Discord.Client();
const MrFOG388= new Discord.Client();
const MrFOG389= new Discord.Client();
const MrFOG390= new Discord.Client();
const MrFOG391= new Discord.Client();
const MrFOG392= new Discord.Client();
const MrFOG393= new Discord.Client();
const MrFOG394= new Discord.Client();
const MrFOG395= new Discord.Client();
const MrFOG396= new Discord.Client();
const MrFOG397= new Discord.Client();
const MrFOG398= new Discord.Client();
const MrFOG399= new Discord.Client();
const MrFOG400= new Discord.Client();
const MrFOG401= new Discord.Client();
const MrFOG402= new Discord.Client();
const MrFOG403= new Discord.Client();
const MrFOG404= new Discord.Client();
const MrFOG405= new Discord.Client();
const MrFOG406= new Discord.Client();
const MrFOG407= new Discord.Client();
const MrFOG408= new Discord.Client();
const MrFOG409= new Discord.Client();
const MrFOG410= new Discord.Client();
const MrFOG411= new Discord.Client();
const MrFOG412= new Discord.Client();
const MrFOG413= new Discord.Client();
const MrFOG414= new Discord.Client();
const MrFOG415= new Discord.Client();
const MrFOG416= new Discord.Client();
const MrFOG417= new Discord.Client();
const MrFOG418= new Discord.Client();
const MrFOG419= new Discord.Client();
const MrFOG420= new Discord.Client();
const MrFOG421= new Discord.Client();
const MrFOG422= new Discord.Client();
const MrFOG423= new Discord.Client();
const MrFOG424= new Discord.Client();
const MrFOG425= new Discord.Client();
const MrFOG426= new Discord.Client();
const MrFOG427= new Discord.Client();
const MrFOG428= new Discord.Client();
const MrFOG429= new Discord.Client();
const MrFOG430= new Discord.Client();
const MrFOG431= new Discord.Client();
const MrFOG432= new Discord.Client();
const MrFOG433= new Discord.Client();
const MrFOG434= new Discord.Client();
const MrFOG435= new Discord.Client();
const MrFOG436= new Discord.Client();
const MrFOG437= new Discord.Client();
const MrFOG438= new Discord.Client();
const MrFOG439= new Discord.Client();
const MrFOG440= new Discord.Client();
const MrFOG441= new Discord.Client();
const MrFOG442= new Discord.Client();
const MrFOG443= new Discord.Client();
const MrFOG444= new Discord.Client();
const MrFOG445= new Discord.Client();
const MrFOG446= new Discord.Client();
const MrFOG447= new Discord.Client();
const MrFOG448= new Discord.Client();
const MrFOG449= new Discord.Client();
const MrFOG450= new Discord.Client();
const MrFOG451= new Discord.Client();
const MrFOG452= new Discord.Client();
const MrFOG453= new Discord.Client();
const MrFOG454= new Discord.Client();
const MrFOG455= new Discord.Client();
const MrFOG456= new Discord.Client();
const MrFOG457= new Discord.Client();
const MrFOG458= new Discord.Client();
const MrFOG459= new Discord.Client();
const MrFOG460= new Discord.Client();
const MrFOG461= new Discord.Client();
const MrFOG462= new Discord.Client();
const MrFOG463= new Discord.Client();
const MrFOG464= new Discord.Client();
const MrFOG465= new Discord.Client();
const MrFOG466= new Discord.Client();
const MrFOG467= new Discord.Client();
const MrFOG468= new Discord.Client();
const MrFOG469= new Discord.Client();
const MrFOG470= new Discord.Client();
const MrFOG471= new Discord.Client();
const MrFOG472= new Discord.Client();
const MrFOG473= new Discord.Client();
const MrFOG474= new Discord.Client();
const MrFOG475= new Discord.Client();
const MrFOG476= new Discord.Client();
const MrFOG477= new Discord.Client();
const MrFOG478= new Discord.Client();
const MrFOG479= new Discord.Client();
const MrFOG480= new Discord.Client();
const MrFOG481= new Discord.Client();
const MrFOG482= new Discord.Client();
const MrFOG483= new Discord.Client();
const MrFOG484= new Discord.Client();
const MrFOG485= new Discord.Client();
const MrFOG486= new Discord.Client();
const MrFOG487= new Discord.Client();
const MrFOG488= new Discord.Client();
const MrFOG489= new Discord.Client();
const MrFOG490= new Discord.Client();
const MrFOG491= new Discord.Client();
const MrFOG492= new Discord.Client();
const MrFOG493= new Discord.Client();
const MrFOG494= new Discord.Client();
const MrFOG495= new Discord.Client();
const MrFOG496= new Discord.Client();
const MrFOG497= new Discord.Client();
const MrFOG498= new Discord.Client();
const MrFOG499= new Discord.Client();
const MrFOG500= new Discord.Client();
const MrFOG501= new Discord.Client();
const MrFOG502= new Discord.Client();
const MrFOG503= new Discord.Client();
const MrFOG504= new Discord.Client();
const MrFOG505= new Discord.Client();
const MrFOG506= new Discord.Client();
const MrFOG507= new Discord.Client();
const MrFOG508= new Discord.Client();
const MrFOG509= new Discord.Client();
const MrFOG510= new Discord.Client();
const MrFOG511= new Discord.Client();
const MrFOG512= new Discord.Client();
const MrFOG513= new Discord.Client();
const MrFOG514= new Discord.Client();
const MrFOG515= new Discord.Client();
const MrFOG516= new Discord.Client();
const MrFOG517= new Discord.Client();
const MrFOG518= new Discord.Client();
const MrFOG519= new Discord.Client();
const MrFOG520= new Discord.Client();
const MrFOG521= new Discord.Client();
const MrFOG522= new Discord.Client();
const MrFOG523= new Discord.Client();
const MrFOG524= new Discord.Client();
const MrFOG525= new Discord.Client();
const MrFOG526= new Discord.Client();
const MrFOG527= new Discord.Client();
const MrFOG528= new Discord.Client();
const MrFOG529= new Discord.Client();
const MrFOG530= new Discord.Client();
const MrFOG531= new Discord.Client();
const MrFOG532= new Discord.Client();
const MrFOG533= new Discord.Client();
const MrFOG534= new Discord.Client();
const MrFOG535= new Discord.Client();
const MrFOG536= new Discord.Client();
const MrFOG537= new Discord.Client();
const MrFOG538= new Discord.Client();
const MrFOG539= new Discord.Client();
const MrFOG540= new Discord.Client();
const MrFOG541= new Discord.Client();
const MrFOG542= new Discord.Client();
const MrFOG543= new Discord.Client();
const MrFOG544= new Discord.Client();
const MrFOG545= new Discord.Client();
const MrFOG546= new Discord.Client();
const MrFOG547= new Discord.Client();
const MrFOG548= new Discord.Client();
const MrFOG549= new Discord.Client();
const MrFOG550= new Discord.Client();
const MrFOG551= new Discord.Client();
const MrFOG552= new Discord.Client();
const MrFOG553= new Discord.Client();
const MrFOG554= new Discord.Client();
const MrFOG555= new Discord.Client();
const MrFOG556= new Discord.Client();
const MrFOG557= new Discord.Client();
const MrFOG558= new Discord.Client();
const MrFOG559= new Discord.Client();
const MrFOG560= new Discord.Client();
const MrFOG561= new Discord.Client();
const MrFOG562= new Discord.Client();
const MrFOG563= new Discord.Client();
const MrFOG564= new Discord.Client();
const MrFOG565= new Discord.Client();
const MrFOG566= new Discord.Client();
const MrFOG567= new Discord.Client();
const MrFOG568= new Discord.Client();
const MrFOG569= new Discord.Client();
const MrFOG570= new Discord.Client();
const MrFOG571= new Discord.Client();
const MrFOG572= new Discord.Client();
const MrFOG573= new Discord.Client();
const MrFOG574= new Discord.Client();
const MrFOG575= new Discord.Client();
const MrFOG576= new Discord.Client();
const MrFOG577= new Discord.Client();
const MrFOG578= new Discord.Client();
const MrFOG579= new Discord.Client();
const MrFOG580= new Discord.Client();
const MrFOG581= new Discord.Client();
const MrFOG582= new Discord.Client();
const MrFOG583= new Discord.Client();
const MrFOG584= new Discord.Client();
const MrFOG585= new Discord.Client();
const MrFOG586= new Discord.Client();
const MrFOG587= new Discord.Client();
const MrFOG588= new Discord.Client();
const MrFOG589= new Discord.Client();
const MrFOG590= new Discord.Client();
const MrFOG591= new Discord.Client();
const MrFOG592= new Discord.Client();
const MrFOG593= new Discord.Client();
const MrFOG594= new Discord.Client();
const MrFOG595= new Discord.Client();
const MrFOG596= new Discord.Client();
const MrFOG597= new Discord.Client();
const MrFOG598= new Discord.Client();
const MrFOG599= new Discord.Client();
const MrFOG600= new Discord.Client();




















































MrFOG1.login("");
MrFOG2.login("");
MrFOG3.login("");
MrFOG4.login("");
MrFOG5.login("");
MrFOG6.login("");
MrFOG7.login("");
MrFOG8.login("");
MrFOG9.login("");
MrFOG10.login("");
MrFOG11.login("");
MrFOG12.login("");
MrFOG13.login("");
MrFOG14.login("");
MrFOG15.login("");
MrFOG16.login("");
MrFOG17.login("");
MrFOG18.login("");
MrFOG19.login("");
MrFOG20.login("");
MrFOG21.login("");
MrFOG22.login("");
MrFOG23.login("");
MrFOG24.login("");
MrFOG25.login("");
MrFOG26.login("");
MrFOG27.login("");
MrFOG28.login("");
MrFOG29.login("");
MrFOG30.login("");
MrFOG31.login("");
MrFOG32.login("");
MrFOG33.login("");
MrFOG34.login("");
MrFOG35.login("");
MrFOG36.login("");
MrFOG37.login("");
MrFOG38.login("");
MrFOG39.login("");
MrFOG40.login("");
MrFOG41.login("");
MrFOG42.login("");
MrFOG43.login("");
MrFOG44.login("");
MrFOG45.login("");
MrFOG46.login("");
MrFOG47.login("");
MrFOG48.login("");
MrFOG49.login("");
MrFOG50.login("");
MrFOG51.login("");
MrFOG52.login("");
MrFOG53.login("");
MrFOG54.login("");
MrFOG55.login("");
MrFOG56.login("");
MrFOG57.login("");
MrFOG58.login("");
MrFOG59.login("");
MrFOG60.login("");
MrFOG61.login("");
MrFOG62.login("");
MrFOG63.login("");
MrFOG64.login("");
MrFOG65.login("");
MrFOG66.login("");
MrFOG67.login("");
MrFOG68.login("");
MrFOG69.login("");
MrFOG70.login("");
MrFOG71.login("");
MrFOG72.login("");
MrFOG73.login("");
MrFOG74.login("");
MrFOG75.login("");
MrFOG76.login("");
MrFOG77.login("");
MrFOG78.login("");
MrFOG79.login("");
MrFOG80.login("");
MrFOG81.login("");
MrFOG82.login("");
MrFOG83.login("");
MrFOG84.login("");
MrFOG85.login("");
MrFOG86.login("");
MrFOG87.login("");
MrFOG88.login("");
MrFOG89.login("");
MrFOG90.login("");
MrFOG91.login("");
MrFOG92.login("");
MrFOG93.login("");
MrFOG94.login("");
MrFOG95.login("");
MrFOG96.login("");
MrFOG97.login("");
MrFOG98.login("");
MrFOG99.login("");
MrFOG100.login("");
MrFOG101.login("");
MrFOG102.login("");
MrFOG103.login("");
MrFOG104.login("");
MrFOG105.login("");
MrFOG106.login("");
MrFOG107.login("");
MrFOG108.login("");
MrFOG109.login("");
MrFOG110.login("");
MrFOG111.login("");
MrFOG112.login("");
MrFOG113.login("");
MrFOG114.login("");
MrFOG115.login("");
MrFOG116.login("");
MrFOG117.login("");
MrFOG118.login("");
MrFOG119.login("");
MrFOG120.login("");
MrFOG121.login("");
MrFOG21.login("");
MrFOG22.login("");
MrFOG23.login("");
MrFOG24.login("");
MrFOG25.login("");
MrFOG26.login("");
MrFOG27.login("");
MrFOG28.login("");
MrFOG29.login("");
MrFOG30.login("");
MrFOG31.login("");
MrFOG32.login("");
MrFOG33.login("");
MrFOG34.login("");
MrFOG35.login("");
MrFOG36.login("");
MrFOG37.login("");
MrFOG38.login("");
MrFOG39.login("");
MrFOG40.login("");
MrFOG41.login("");
MrFOG42.login("");
MrFOG43.login("");
MrFOG44.login("");
MrFOG45.login("");
MrFOG46.login("");
MrFOG47.login("");
MrFOG48.login("");
MrFOG49.login("");
MrFOG50.login("");
MrFOG51.login("");
MrFOG52.login("");
MrFOG53.login("");
MrFOG54.login("");
MrFOG55.login("");
MrFOG56.login("");
MrFOG57.login("");
MrFOG58.login("");
MrFOG59.login("");
MrFOG60.login("");
MrFOG61.login("");
MrFOG62.login("");
MrFOG63.login("");
MrFOG64.login("");
MrFOG65.login("");
MrFOG66.login("");
MrFOG67.login("");
MrFOG68.login("");
MrFOG69.login("");
MrFOG70.login("");
MrFOG71.login("");
MrFOG72.login("");
MrFOG73.login("");
MrFOG74.login("");
MrFOG75.login("");
MrFOG76.login("");
MrFOG77.login("");
MrFOG78.login("");
MrFOG79.login("");
MrFOG80.login("");
MrFOG81.login("");
MrFOG82.login("");
MrFOG83.login("");
MrFOG84.login("");
MrFOG85.login("");
MrFOG86.login("");
MrFOG87.login("");
MrFOG88.login("");
MrFOG89.login("");
MrFOG90.login("");
MrFOG91.login("");
MrFOG92.login("");
MrFOG93.login("");
MrFOG94.login("");
MrFOG95.login("");
MrFOG96.login("");
MrFOG97.login("");
MrFOG98.login("");
MrFOG99.login("");
MrFOG100.login("");
MrFOG101.login("");
MrFOG102.login("");
MrFOG103.login("");
MrFOG104.login("");
MrFOG105.login("");
MrFOG106.login("");
MrFOG107.login("");
MrFOG108.login("");
MrFOG109.login("");
MrFOG110.login("ODA1NjA4ODk0ODA5MjQzNjQ4.YBdZPw.g6_FgtIpObYkET0Pt20gNaZZCgQ");

























